name: Git Tag via Commit Id

on:
  workflow_dispatch:
    inputs:
      TAG_ID:
        description: Tag ID
        required: true

jobs:
  production:
    name: Tagging
    runs-on: self-hosted
    env:
      ci_tag_id: ${{ inputs.TAG_ID }}
    steps:
      - name: Commands
        shell: bash
        run: |
          git checkout main
          git status
          git pull origin main
          git fetch --all
          git tag ${{ inputs.TAG_ID }}
          git push origin ${{ inputs.TAG_ID }}
