name: Git Tag via Commit Id

on:
  workflow_dispatch:
    inputs:
      TAG_ID:
        description: Tag ID
        required: true

jobs:
  production:
    name: Tagging
    runs-on: ubuntu-latest
    env:
      ci_tag_id: ${{ inputs.TAG_ID }}
    steps:
      - name: Check workspace
        shell: bash 
        run: |
          echo "Your current workspace is %CD%"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          dir ${{ github.workspace }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
         
      - name: Commands
        shell: bash
        run: |
          git checkout main
          git status
          git pull origin main
          git fetch --all
          git tag ${{ inputs.TAG_ID }}
          git push origin ${{ inputs.TAG_ID }}
